# https://www.gitpod.io/docs/references/gitpod-yml

# Commands to start on workspace startup
#tasks:
#  - init: yarn install
#    command: yarn build

# Ports to expose on workspace startup
ports:
  - port: 8000
    #onOpen: open-preview
    visibility: public
  - port: 8001
    #onOpen: open-preview
    visibility: public


# https://open-vsx.org/
# keep these in sync with ~/.vscode/extensions.json to support people with local dev environments
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - streetsidesoftware.code-spell-checker
    - 42Crunch.vscode-openapi
    - ms-vscode.makefile-tools
